language: ruby
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ree
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - rbx-18mode
  - rbx-19mode
  - ree

